openapi: 3.0.0
info:
  title: My App API
  version: 1.0.0
paths:
  /auth/login:
    post:
      operationId: authLogin
      summary: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /auth/logout:
    post:
      operationId: authLogout
      summary: ログアウト
      responses:
        "200":
          description: ログアウト成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /auth/signin:
    post:
      operationId: authSignin
      summary: サインイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: サインイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /auth/me:
    get:
      operationId: authMe
      summary: 認証情報取得
      responses:
        "200":
          description: 認証情報取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  me:
                    $ref: "#/components/schemas/AuthMe"
                    nullable: true
  /admin/users:
    get:
      operationId: getAdminUsers
      summary: ユーザー情報一覧取得
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: ユーザー情報一覧取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  page:
                    type: number
                  limit:
                    type: number
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
                required:
                  - total
                  - page
                  - limit
                  - users
    post:
      operationId: postAdminUser
      summary: 新規ユーザー作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                department:
                  type: string
                jobTitle:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                joinedOn:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
                    enum:
                      - user
                      - admin
              required:
                - name
                - email
                - roles
      responses:
        "201":
          description: 新規ユーザー作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      operationId: deleteAdminUsers
      summary: ユーザー削除
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
              required:
                - id
      responses:
        "200":
          description: ユーザー削除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /admin/users/{id}:
    put:
      operationId: putAdminUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                department:
                  type: string
                jobTitle:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                joinedOn:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
                    enum:
                      - user
                      - admin
              required:
                - name
                - email
                - roles
      responses:
        "200":
          description: ユーザー情報更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      operationId: deleteAdminUser
      summary: ユーザー削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: ユーザー削除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
components:
  schemas:
    AuthMe:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        roles:
          type: array
          items:
            type: string
            enum:
              - user
              - admin
        lastLoginAt:
          type: string
          format: date
      required:
        - id
        - name
        - roles
        - lastLoginAt
    User:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        department:
          type: string
        jobTitle:
          type: string
        phone:
          type: string
        email:
          type: string
        joinedOn:
          type: string
          format: date
        roles:
          type: array
          items:
            type: string
            enum:
              - user
              - admin
      required:
        - id
        - name
        - department
        - jobTitle
        - phone
        - email
        - joinedOn
        - roles
