openapi: 3.0.0
info:
  title: 勤怠
  version: 1.0.0

paths:
  /attendances:
    # 勤怠情報取得
    get:
      operationId: getAttendances
      summary: 勤怠情報取得
      parameters:
        - name: month
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: ユーザー情報一覧取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  attendances:
                    type: array
                    items:
                      $ref: "#/components/schemas/Attendance"
                required: ["attendances"]

components:
  schemas:
    Attendance:
      type: object
      properties:
        date:
          type: string
          format: date
        clockIn:
          type: string
        clockOut:
          type: string
        break:
          type: string
        type:
          type: string
          enum: ["working", "onLeave", "leftEarly", "other"]
        note:
          type: string
      required: ["date", "clockIn", "clockOut", "break", "type", "note"]
