/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ユーザー管理
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import useSwr from "swr";
import type { Arguments, Key, SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

export type UserRolesItem = (typeof UserRolesItem)[keyof typeof UserRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export interface User {
  id: number;
  name: string;
  department: string;
  jobTitle?: string;
  phone: string;
  email: string;
  joinedOn: string;
  roles: UserRolesItem[];
}

export type GetAdminUsersParams = {
  q?: string;
  page?: number;
};

export type GetAdminUsers200 = {
  total: number;
  page: number;
  limit: number;
  users: User[];
};

export type PostAdminUserBodyRolesItem =
  (typeof PostAdminUserBodyRolesItem)[keyof typeof PostAdminUserBodyRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAdminUserBodyRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export type PostAdminUserBody = {
  name: string;
  department: string;
  jobTitle?: string;
  phone: string;
  email: string;
  joinedOn: string;
  roles: PostAdminUserBodyRolesItem[];
};

export type PutAdminUserBodyRolesItem =
  (typeof PutAdminUserBodyRolesItem)[keyof typeof PutAdminUserBodyRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutAdminUserBodyRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export type PutAdminUserBody = {
  name: string;
  department: string;
  jobTitle?: string;
  phone: string;
  email: string;
  joinedOn: string;
  roles: PutAdminUserBodyRolesItem[];
};

export type DeleteAdminUser204 = {
  message: string;
};

/**
 * @summary ユーザー情報一覧取得
 */
export const getAdminUsers = (
  params?: GetAdminUsersParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetAdminUsers200>> => {
  return axios.get(`/api/admin/users`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetAdminUsersKey = (params?: GetAdminUsersParams) =>
  [`/api/admin/users`, ...(params ? [params] : [])] as const;

export type GetAdminUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminUsers>>
>;
export type GetAdminUsersQueryError = AxiosError<unknown>;

/**
 * @summary ユーザー情報一覧取得
 */
export const useGetAdminUsers = <TError = AxiosError<unknown>>(
  params?: GetAdminUsersParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getAdminUsers>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    axios?: AxiosRequestConfig;
  },
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAdminUsersKey(params) : null));
  const swrFn = () => getAdminUsers(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary 新規ユーザー作成
 */
export const postAdminUser = (
  postAdminUserBody: PostAdminUserBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<User>> => {
  return axios.post(`/api/admin/users`, postAdminUserBody, options);
};

export const getPostAdminUserMutationFetcher = (
  options?: AxiosRequestConfig,
) => {
  return (_: Key, { arg }: { arg: PostAdminUserBody }) => {
    return postAdminUser(arg, options);
  };
};
export const getPostAdminUserMutationKey = () => [`/api/admin/users`] as const;

export type PostAdminUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAdminUser>>
>;
export type PostAdminUserMutationError = AxiosError<unknown>;

/**
 * @summary 新規ユーザー作成
 */
export const usePostAdminUser = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAdminUser>>,
    TError,
    Key,
    PostAdminUserBody,
    Awaited<ReturnType<typeof postAdminUser>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAdminUserMutationKey();
  const swrFn = getPostAdminUserMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const putAdminUser = (
  id: number,
  putAdminUserBody: PutAdminUserBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<User>> => {
  return axios.put(`/api/admin/users/${id}`, putAdminUserBody, options);
};

export const getPutAdminUserMutationFetcher = (
  id: number,
  options?: AxiosRequestConfig,
) => {
  return (_: Key, { arg }: { arg: PutAdminUserBody }) => {
    return putAdminUser(id, arg, options);
  };
};
export const getPutAdminUserMutationKey = (id: number) =>
  [`/api/admin/users/${id}`] as const;

export type PutAdminUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAdminUser>>
>;
export type PutAdminUserMutationError = AxiosError<unknown>;

export const usePutAdminUser = <TError = AxiosError<unknown>>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof putAdminUser>>,
      TError,
      Key,
      PutAdminUserBody,
      Awaited<ReturnType<typeof putAdminUser>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  },
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPutAdminUserMutationKey(id);
  const swrFn = getPutAdminUserMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary ユーザー削除
 */
export const deleteAdminUser = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DeleteAdminUser204>> => {
  return axios.delete(`/api/admin/users/${id}`, options);
};

export const getDeleteAdminUserMutationFetcher = (
  id: number,
  options?: AxiosRequestConfig,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteAdminUser(id, options);
  };
};
export const getDeleteAdminUserMutationKey = (id: number) =>
  [`/api/admin/users/${id}`] as const;

export type DeleteAdminUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminUser>>
>;
export type DeleteAdminUserMutationError = AxiosError<unknown>;

/**
 * @summary ユーザー削除
 */
export const useDeleteAdminUser = <TError = AxiosError<unknown>>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteAdminUser>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteAdminUser>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  },
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteAdminUserMutationKey(id);
  const swrFn = getDeleteAdminUserMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
