/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 勤怠
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import useSwr from "swr";
import type { Key, SWRConfiguration } from "swr";

export type AttendanceType =
  (typeof AttendanceType)[keyof typeof AttendanceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttendanceType = {
  working: "working",
  onLeave: "onLeave",
  leftEarly: "leftEarly",
  other: "other",
  holiday: "holiday",
} as const;

export interface Attendance {
  date: string;
  clockIn: string;
  clockOut: string;
  break: string;
  type: AttendanceType;
  note: string;
}

export type GetAttendancesParams = {
  month?: string;
};

export type GetAttendances200 = {
  attendances: Attendance[];
};

/**
 * @summary 勤怠情報取得
 */
export const getAttendances = (
  params?: GetAttendancesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetAttendances200>> => {
  return axios.get(`/api/attendances`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetAttendancesKey = (params?: GetAttendancesParams) =>
  [`/api/attendances`, ...(params ? [params] : [])] as const;

export type GetAttendancesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAttendances>>
>;
export type GetAttendancesQueryError = AxiosError<unknown>;

/**
 * @summary 勤怠情報取得
 */
export const useGetAttendances = <TError = AxiosError<unknown>>(
  params?: GetAttendancesParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getAttendances>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    axios?: AxiosRequestConfig;
  },
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAttendancesKey(params) : null));
  const swrFn = () => getAttendances(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
