/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * マイデータ
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import useSwr from "swr";
import type { Key, SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

export type MyDataRolesItem =
  (typeof MyDataRolesItem)[keyof typeof MyDataRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyDataRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export interface MyData {
  id: number;
  name: string;
  department: string;
  jobTitle: string;
  phone: string;
  email: string;
  joinedOn: string;
  roles: MyDataRolesItem[];
}

export type PutMyDataBody = {
  name: string;
  phone?: string;
  email: string;
};

export type PutMyDataPasswordBody = {
  password: string;
  newPassword: string;
};

export type PutMyDataPassword200 = {
  message: string;
};

/**
 * @summary マイデータ取得
 */
export const getMyData = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<MyData>> => {
  return axios.get(`/api/my-data`, options);
};

export const getGetMyDataKey = () => [`/api/my-data`] as const;

export type GetMyDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyData>>
>;
export type GetMyDataQueryError = AxiosError<unknown>;

/**
 * @summary マイデータ取得
 */
export const useGetMyData = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getMyData>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetMyDataKey() : null));
  const swrFn = () => getMyData(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary マイデータ更新
 */
export const putMyData = (
  putMyDataBody: PutMyDataBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<MyData>> => {
  return axios.put(`/api/my-data`, putMyDataBody, options);
};

export const getPutMyDataMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: PutMyDataBody }) => {
    return putMyData(arg, options);
  };
};
export const getPutMyDataMutationKey = () => [`/api/my-data`] as const;

export type PutMyDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof putMyData>>
>;
export type PutMyDataMutationError = AxiosError<unknown>;

/**
 * @summary マイデータ更新
 */
export const usePutMyData = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof putMyData>>,
    TError,
    Key,
    PutMyDataBody,
    Awaited<ReturnType<typeof putMyData>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPutMyDataMutationKey();
  const swrFn = getPutMyDataMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary パスワード更新
 */
export const putMyDataPassword = (
  putMyDataPasswordBody: PutMyDataPasswordBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PutMyDataPassword200>> => {
  return axios.put(`/api/my-data/password`, putMyDataPasswordBody, options);
};

export const getPutMyDataPasswordMutationFetcher = (
  options?: AxiosRequestConfig,
) => {
  return (_: Key, { arg }: { arg: PutMyDataPasswordBody }) => {
    return putMyDataPassword(arg, options);
  };
};
export const getPutMyDataPasswordMutationKey = () =>
  [`/api/my-data/password`] as const;

export type PutMyDataPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof putMyDataPassword>>
>;
export type PutMyDataPasswordMutationError = AxiosError<unknown>;

/**
 * @summary パスワード更新
 */
export const usePutMyDataPassword = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof putMyDataPassword>>,
    TError,
    Key,
    PutMyDataPasswordBody,
    Awaited<ReturnType<typeof putMyDataPassword>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPutMyDataPasswordMutationKey();
  const swrFn = getPutMyDataPasswordMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
