/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * マイデータ
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import useSwr from "swr";
import type { Key, SWRConfiguration } from "swr";

export type MyDataRolesItem =
  (typeof MyDataRolesItem)[keyof typeof MyDataRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyDataRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export interface MyData {
  id: number;
  name: string;
  department: string;
  jobTitle: string;
  phone: string;
  email: string;
  joinedOn: string;
  roles: MyDataRolesItem[];
}

/**
 * @summary マイデータ取得
 */
export const getMyData = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<MyData>> => {
  return axios.get(`/api/my-data`, options);
};

export const getGetMyDataKey = () => [`/api/my-data`] as const;

export type GetMyDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyData>>
>;
export type GetMyDataQueryError = AxiosError<unknown>;

/**
 * @summary マイデータ取得
 */
export const useGetMyData = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getMyData>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetMyDataKey() : null));
  const swrFn = () => getMyData(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
